# -*- coding: utf-8 -*-
"""
Dicionários de correção para padronização da coluna PRODUTO.
Contém regras de segmentação, correções ortográficas e fuzzy matching.
"""

# ==============================================================================
#      CONJUNTOS PARA LÓGICA DE SEGMENTAÇÃO
# ==============================================================================

# Preposições e conectores
PREP = {"DE", "DO", "DA", "DOS", "DAS", "E", "OU"}

# Nomes de sais
SAL_NOMES = {
    "CLORIDRATO", "BROMIDRATO", "BROMETO", "IODETO", "NITRATO", "SULFATO", "FOSFATO", "MALEATO", "TARTARATO",
    "BENZATINA", "COLESTIRAMINA", "PENTAHIDRATADA", "PENTAHIDRATADO", "MICRONIZADO", "MICRONIZADA", "RESINATO",
    "LACTATO", "ACETATO", "CITRATO", "CARBONATO", "GLUCONATO", "DIGLUCONATO", "BESILATO", "MESILATO", "CLAVULANATO",
    "SUCCINATO", "HEMI-HIDRATADO", "TRIHIDRATADO", "MONOHIDRATADO", "DIHIDRATADO", "ANIDRO", "ANIDRA",
    "SESQUIDRATADO", "SESQUIDRATADA", "ISETIONATO", "DIPROPIONATO", "HEMIEPTAIDRATADO", "HEMIEPTAIDRATADA",
    "TRIHIDRATADA", "DIHIDRATADA", "DESOPROXILA", "DIMEGLUMINA", "ZINCICO", "ZINCICA",
}

# Formas de sal
SAL_FORMAS = {
    "SODICO", "SODICA", "POTASSICO", "POTASSICA", "MAGNESICO", "MAGNESICA", "SODIO", "POTASSIO", 
    "CALCICA", "CALCICO", "DISSODICO", "DISSODICA", "DIETILAMONIO"
}

# Qualificadores
QUALIFICADORES = {
    "GOTAS", "PEDIATRICO", "ADULTO", "INFANTIL", "COMPOSTO", "HCT", "TROMETAMOL", "TROMETAMINA", 
    "ACETONIDA", "SALICILICO", "SALICILICA", "CILEXETILA", "CILEXETIL", "MEDOXOMILA", "OLAMINA"
}

# Conectores especiais
CONECTORES = {"N", "N-BUTIL", "BUTIL"}

# Sufixos com letra permitidos
POSFIXO_LETRA_OK = {"POLIMIXINA", "VITAMINA"}

# Conjunto consolidado de termos que não devem separar
NAO_SEPARA = PREP | SAL_NOMES | SAL_FORMAS | QUALIFICADORES | CONECTORES

# ==============================================================================
#      DICIONÁRIO DE CORREÇÕES ORTOGRÁFICAS
# ==============================================================================

DICIONARIO_CORRECAO_PRODUTO = {
    "ESOMEPRAZOL MAGNESIO": "ESOMEPRAZOL MAGNESICO",
    "PANTOPRAZOL SODICO SESQUI HIDRATADO": "PANTOPRAZOL SODICO SESQUIDRATADO",
    "SESQUIHIDRATADO": "",
    "CAXUMA": "CAXUMBA",
    "GETAMICINA": "GENTAMICINA",
    "CLOIDRATO": "CLORIDRATO",
    "DROSPERINONA": "DROSPIRENONA",
}

# ==============================================================================
#      REGRAS DE FUSÃO (PRÉ-PROCESSAMENTO)
# ==============================================================================

import re

PRE_REPLACERS = [
    (re.compile(r"\bBROMETO\s+DE\s+N\s*-?\s*BUTIL(?:E)?\s+ESCOPOLAMINA\b"), "BROMETO DE N-BUTILESCOPOLAMINA"),
    (re.compile(r"\bN\s*-?\s*BUTIL(?:E)?\s+ESCOPOLAMINA\b"), "N-BUTILESCOPOLAMINA"),
    (re.compile(r"\bETINIL\s+ESTRADIOL\b"), "ETINILESTRADIOL"),
    (re.compile(r"\bTROMETAMINA\s+DE\s+CETOROLACO\b"), "CETOROLACO TROMETAMOL"),
]

# ==============================================================================
#      REGRAS DE CORREÇÃO FINAL (PÓS-PROCESSAMENTO)
# ==============================================================================

POST_FIX_RULES = [
    (r"\bBACITRACINA\s*\+\s*SULFATO\s+DE\s+NEOMICINA\b", "BACITRACINA ZINCICA + SULFATO DE NEOMICINA"),
    (r"\bACETONIDA\s+TRIANCINOLONA\b", "ACETONIDO DE TRIANCINOLONA"),
    (r"\bCLORIDRATODE\s*\+?\s*DONEPEZILA\b", "CLORIDRATO DE DONEPEZILA"),
    (r"\bLEVOFLOXACINO\s*(\+?\s*HEMIHIDRATADO)\b", "LEVOFLOXACINO HEMI-HIDRATADO"),
    (r"\bDICLOFENACO\s+DE\s+(COLESTIRAMINA|DIETILAMONIO)\b", r"DICLOFENACO \1"),
    (r"\bPROPIONATO\s+DE\s+CLOBETASOL\s*\+\s*G\b", "PROPIONATO DE CLOBETASOL"),
    (r"\bPROPIONATO\s*\+\s*CLOBETASOL\b", "PROPIONATO DE CLOBETASOL"),
    (r"\bPIPERACICLINA\b", "PIPERACILINA"),
    (r"\bPEMETREXEDE\s+DISSODICO\s*\+\s*HEPTAHIDRATADO\b", "PEMETREXEDE DISSODICO HEPTAHIDRATADO"),
    (r"\bFOSF\s*\+\s*CLINDAMICINA\b", "FOSFATO DE CLINDAMICINA"),
    (r"\bCLOR\s*\+\s*([A-ZÇ]+)\b", r"CLORIDRATO DE \1"),
    (r"\b(BROMETO)\s+(IPRATROPIO)\b", r"\1 DE \2"),
    (r"\bACIDO\s*\+\s*", "ACIDO "),
    # Padrões a remover
    (r"\b\d+\s*(MG|ML|G|MCG|UI|MCI)\b", ""),
    (r"\bHEMIPENTAIDRATAD[AO]\b", ""),
    (r"\b(SODICA|DISSODICA|HEMIEPTAIDRATADA|SUSPENSAO|POMADA)\b", ""),
]

# ==============================================================================
#      DICIONÁRIO SUGERIDO (FUZZY MATCHING)
# ==============================================================================

DIC_SUGERIDO_PRODUTO = {
    "CLIOQUINOL/": "CLIOQUINOL",
    "VACINA ADSORVIDA DIFTERIA, TETANO E PERTUSIS (ACELULAR)": "VACINA ADSORVIDA DIFTERIA, TETANO E PERTUSSIS (ACELULAR)",
    "VACINA INFLUENZA TRIVALENTE (FRAGMENTADA E INATIVADA)": "VACINA INFLUENZA TRIVALENTE ( FRAGMENTADA E INATIVADA )",
    "VACINA INFLUENZA TRIVALENTE (FRAGMENTADA, INATIVADA)": "VACINA INFLUENZA TRIVALENTE ( FRAGMENTADA E INATIVADA )",
    "VACINA RAIVA(INATIVADA)": "VACINA RAIVA (INATIVADA)",
    "VACINA SARAMPO, CAXUMBA, RUBEOLA (ATENUADA)": "VACINA SARAMPO, CAXUMBA E RUBEOLA (ATENUADA)",
    "LAFEPE -ZIDOVUDINA": "LAFEPE - ZIDOVUDINA",
    "LIPIGRAN": "LIPIGRAND",
    "SIGMA-CLAV BD": "SIGMA CLAV BD",
    "UNI-DIAZEPAX": "UNI DIAZEPAX",
    "CASTANHA DA INDIA EC": "CASTANHA DA INDIA",
    "ANA - FLEX": "ANA-FLEX",
    "AGUA PARA INJECAO DILUENTE": "AGUA PARA INJECAO",
    "ALBUMINA HUMANA GRIFOLS 20%": "ALBUMINA HUMANA GRIFOLS",
    "FARMANGUINHOS -LAMIVUDINA": "FAR-MANGUINHOS-LAMIVUDINA",
    "FARMANGUINHOS ISONIAZIDA": "FARMANGUINHOS - ISONIAZIDA",
    "FARMARIN CPHD": "CPHD FARMARIN",
    "FURP -CARBAMAZEPINA": "FURP-CARBAMAZEPINA",
    "LAFEPE ZIDOVUDINA": "LAFEPE - ZIDOVUDINA",
    "SORO ANTIBOTROPICO/CROTALICO": "SORO ANTIBOTROPICO-CROTALICO",
    "SORO ANTIBOTROPICO/LAQUETICO": "SORO ANTIBOTROPICO-LAQUETICO",
    'ZAARPRESS HTC': 'ZAARPRESS HCT',
    'SESQUIIDRATADO': 'SESQUIHIDRATADO',
    'SESQUIHIIDRATADO': 'SESQUIHIDRATADO',
    'CLORIDRATO DE DILTIAZEN': 'CLORIDRATO DE DILTIAZEM',
    'BENICAR OD': 'BENICAR ODT',
    'DOPROPIZINA': 'DROPROPIZINA',
    "ACETO TRIA SULF NEO GRAM NIST": "ACETONIDO DE TRIANCINOLONA + SULFATO DE NEOMICINA + GRAMICIDINA + NISTATINA",
    'CETOROLACO DE TROMETAMOL': 'CETOROLACO TROMETAMOL',
    'TROMETAMOL CETOROLACO': 'CETOROLACO TROMETAMOL',
    'CLORIDRATO DE FLOUXETINA': 'CLORIDRATO DE FLUOXETINA',
    'CLOROQUINA DIFOSFATO': 'DIFOSFATO DE CLOROQUINA',
    'FLUCIONAZOL': 'FLUCONAZOL',
    'GLIMEPRIDA': 'GLIMEPIRIDA',
    'THIABENDAZOL': 'TIABENDAZOL',
    'CLOROTALIDONA': 'CLORTALIDONA',
    'CIMEGRIPE 77 C': 'CIMEGRIPE 77C',
    'CIPROFLOXACIN0': 'CIPROFLOXACINO',
    'CLOQUINOL': 'CLIOQUINOL',
    "LAFEPE ZIDOVUDINA LAMIVUDINA": "LAFEPE ZIDOVUDINA + LAMIVUDINA",
    'SULFATO NEOMICINA': 'SULFATO DE NEOMICINA',
    'SULFATO SALBUTAMOL': 'SULFATO DE SALBUTAMOL',
    'PREDNISOLON': 'PREDNISOLONA',
    'NITRATO ISOCONAZOL': 'NITRATO DE ISOCONAZOL',
    'NITRATO MICONAZOL': 'NITRATO DE MICONAZOL',
    'MARCLOHREX': 'MARCLORHEX',
    'MALEATO DE DEXCLOFERINAMINA': 'MALEATO DE DEXCLORFENIRAMINA',
    'MALEATO ENALAPRIL': 'MALEATO DE ENALAPRIL',
    'LANZOPRAZOL': 'LANSOPRAZOL',
    'GLICAZIDA': 'GLICLAZIDA',
    'COLISTIMETATO SODICO': 'COLISTIMETATO DE SODIO',
    'CLORIDRATO DE HIDROXIZINE': 'DICLORIDRATO DE HIDROXIZINA',
    'CLORIDRATO DULOXETINA': 'CLORIDRATO DE DULOXETINA',
    'COLECOXIBE': 'CELECOXIBE',
    'B BRAUN SOLUCAO DE RINGER NO3': 'B BRAUN SOLUCAO DE RINGER NO 3',
    'CETOCONAZOL DIPROPIONATO DE BETAMETASONA SULFATO DE NEOMICINA': 'CETOCONAZOL + DIPROPRIONATO DE BETAMETASONA + SULFATO DE NEOMICINA',
    'CLORIDRATO DE CICLOBENZAPRIN': 'CLORIDRATO DE CICLOBENZAPRINA',
    'CLORIDRATO DE GRANISETRONA': 'CLORIDRATO DE GANISETRONA',
    'CLORIDRATO DE TERACICLINA': 'CLORIDRATO DE TETRACICLINA',
    'DIPROPIONATO DE BETAMETASONA': 'DIPROPRIONATO DE BETAMETASONA',
    'LEVOFLOXACINO HEMIHIDRATADO': 'LEVOFLOXACINO HEMI-HIDRATADO',
    'MALEATO DE DEXCLORFENIARAMINA': 'MALEATO DE DEXCLORFENIRAMINA',
    'PANTOPRAZOL MAGNESICO DI HIDRATADO': 'PANTOPRAZOL MAGNESICO DIHIDRATADO',
    'PANTOPRAZOL SODICO SESQUI HIDRATADO': 'PANTOPRAZOL SODICO SESQUIHIDRATADO',
    'PILULAS DE ERVA DE BICHO COMPOSTA IMESCARD': 'PILULAS DE ERVA DE BICHO COMPOSTAS IMESCARD',
    'SUCCINATO SODICO DE METILPREDINISOLONA': 'SUCCINATO SODICO DE METILPREDNISOLONA',
    'SULFATO DE MAGNESIO HEPTAIDRATADO': 'SULFATO DE MAGNESIO HEPTAHIDRATADO',
    'VACINA ADSORVIDA DIFTERIA TETANO E PERTUSIS ACELULAR': 'VACINA ADSORVIDA DIFTERIA TETANO E PERTUSSIS ACELULAR',
    'VACINA INFLUENZA TRIVALENTE FRAGMENTADA INATIVADA': 'VACINA INFLUENZA TRIVALENTE FRAGMENTADA E INATIVADA',
    'VALERATO DE BETAMETASONA SULFATO DE GETAMICINA TOLNAFTATO CLIOQUINOL': 'VALERATO DE BETAMETASONA + SULFATO DE GENTAMICINA + TOLNAFTATO + CLIOQUINOL',
    'BROMETO DE IPRATROPRIO': 'BROMETO DE IPRATROPIO',
    'CITRATO DE ORFENADRINA': 'CITRATO DE ORFENADINA',
    'CITRATO DE SILDENAFILA': 'CITRATO DE SIDENAFILA',
    'CLORIDRATO DE ONDANSENTRONA': 'CLORIDRATO DE ONDANSETRONA',
    'CLORIDRATO DE PROPRANOLOL': 'CLORIDRATO DE PROPANOLOL',
    'FAR MANGUINHOS CAPTOPRIL': 'FARMANGUINHOS CAPTOPRIL',
    'FOSFATO DISSODICO DE BETAMENTASONA': 'FOSFATO DISSODICO DE BETAMETASONA',
    'IQUEGO PROPRANOLOL': 'IQUEGO PROPANOLOL',
    'VITAMIN E': 'VITAMINA E',
    'SULFATO POLIMIXINA B': 'SULFATO DE POLIMIXINA B',
    'TOZOBACTAM SODICO': 'TAZOBACTAM SODICO',
    'TIOABENDAZOL': 'TIABENDAZOL',
    'TRIANCINOLONA DE ACETONIDA': 'TRIANCINOLONA ACETONIDA',
    'TRIAXTON': 'TRIAXON',
    'UNI DEXA': 'UNIDEXA',
    'SOLUCAO DE RINGER COM LACTATO': 'SOLUCAO RINGER COM LACTATO',
    'RIBAVIRIN': 'RIBAVIRINA',
    'MULTIDERM': 'MULTIDERME',
    'LEITE DE MAGNESIA PHILLIPS': 'LEITE DE MAGNESIA DE PHILLIPS',
    'GENTAMICIN': 'GENTAMICINA',
    'GLIBENCAMIDA': 'GLIBENCLAMIDA',
    'CPHD AC 35 C GLICOSE': 'CPHD AC 35 COM GLICOSE',
    'DICLOFENACO COLESTIRAMINA': 'DICLOFENACO DE COLESTIRAMINA',
    'DICLOFENACO DIETILAMONIO': 'DICLOFENACO DE DIETILAMONIO',
    'BACLOFEN': 'BACLOFENO',
    'LQFEX HIDROCLOROTIAZIDA': 'LQFE HIDROCLOROTIAZIDA',
    'PIPERACICLINA SODICA': 'PIPERACILINA SODICA',
    'SULFATO DE GENTAMICINA': 'SULFATO DE GETAMICINA',
    'VACINA SARAMPO CAXUMBA E RUBEOLA ATENUADA': 'VACINA SARAMPO CAXUMBA RUBEOLA ATENUADA',
    'ACETADO DE DEXAMETASONA': 'ACETATO DE DEXAMETASONA',
    'ACETONIDA DE TRIANCINOLONA': 'ACETONIDO DE TRIANCINOLONA',
    'AZITRIMICINA DIHIDRATADA': 'AZITROMICINA DIHIDRATADA',
    'BISSULFATO DE CLOPIDROGEL': 'BISSULFATO DE CLOPIDOGREL',
    'BROMETO DE N BUTILESCOPOLAMINA': 'BROMETO DE N-BUTILESCOPOLAMINA',
    'CLORIDARTO DE MEMANTINA': 'CLORIDRATO DE MEMANTINA',
    'CLORIDRATO DE CEFEPIME': 'CLORIDRATO DE CEFEPIMA',
    'CLORIDRATO DE HIDROXIZINE': 'CLORIDRATO DE HIDROXIZINA',
    'CLORIDRATO DE ISOMETEPTANO': 'CLORIDRATO DE ISOMETEPTENO',
    'DICLOFENACO DE DIETILAMOMIO': 'DICLOFENACO DE DIETILAMONIO',
    'FOSFATO DE SODICO DE PREDNISOLONA': 'FOSFATO SODICO DE PREDNISOLONA',
    'NEO SORO INFANTIL': 'NEOSORO INFANTIL',
    'OLMETEC ANLO': 'OLMETECANLO',
    'LEVONOGESTREL': 'LEVONORGESTREL',
    'LQFE MEBENDAZOL': 'LQFEX MEBENDAZOL',
    'MALEATO DE DEXCLOFERNIRAMINA': 'MALEATO DE DEXCLORFENIRAMINA',
    'MATER FOLIC': 'MATERFOLIC',
    'PANTOPRAZOL SODICO SESQUIDRATADO': 'PANTOPRAZOL SODICO SESQUIHIDRATADO',
    'PROPIONATO DE CLOBETASOL 0': 'PROPIONATO DE CLOBETASOL',
    'RIFAMICINA': 'RIFAMPICINA',
    'RISPERIDON': 'RISPERIDONA',
    'PIPORTIL L 4': 'PIPORTIL L4',
    'PLASMA LYTE': 'PLASMALYTE',
    'PREDINISONA': 'PREDNISONA',
    'VACINA POLIOMIELITE 1 3 ATENUADA': 'VACINA POLIOMIELITE 1 E 3 ATENUADA',
    'XAROPE 44 E': 'XAROPE 44E',
    'OXALATO DE EXCITALOPRAM': 'OXALATO DE ESCITALOPRAM'
}

# ==============================================================================
#      CORREÇÕES DIRECIONADAS (str.replace)
# ==============================================================================

CORRECOES_CONTAINS_PRODUTO = [
    ('.', '', False),
    ('-', ' ', False),
    ('+ HEMI + HIDRATADO', '', False),
    ('+ 0,/G', '', False),
    ('+ 40 + MG/ML + ORAL', '', False),
    ('+ TRI HIDRATADO', '', False),
    ('+ DI HIDRATADO', '', False),
    ('ROCKY + LP', 'ROCKY LP', False),
    ('+ +', '+', False),
    ('+ / +', '+', False),
    ('TRI-HIDRATADA', '', False),
    ('NORFLOXACINO + 400 + MG', 'NORFLOXACINO', False),
    ('TRI-HIDRATADO', '', False),
    ('DI-HIDRATADA', '', False),
    ('DI-HIDRATADO', '', False),
    ('SOLUCAO SOLUCAO', 'SOLUCAO', False),
    ('SOLUCAO DE SOLUCAO', 'SOLUCAO', False),
    ('DE SODIO DE SODIO', 'DE SODIO', False),
    ('MONTELUCASTE SODICO', 'MONTELUCASTE DE SODIO', False),
    ('OLMESARTANA + MEDOXOMILA', 'OLMESARTANA MEDOXOMILA', False),
    ('FOSF + CLINDAMICINA', 'FOSFATO DE CLINDAMICINA', False),
    ('TENOFOVIR + DESOPROXILA', 'TENOFOVIR DESOPROXILA', False),
    ('IBUPROFENO + 200 + MG + COMPRIMIDO + REVESTIDO', 'IBUPROFENO', False),
    ('LOSARTANA + POTASSICA', 'LOSARTANA POTASSICA', False),
    ('SESQUI-HIIDRATADO', '', False),
    ('SESQUIDRATADO', '', False),
    ('TOLNAFTATO/', 'TOLNAFTATO', False),
    ('CETOCONAZOL-MICRONIZADO', 'CETOCONAZOL MICRONIZADO', False),
    ('CICLOPIROX- OLAMINA', 'CICLOPIROX OLAMINA', False),
    ('ANFOTERICINA + B', 'ANFOTERICINA B', False),
    ('CORASTORVA (ATORVASTATINA CALCICA)', 'CORASTORVA', False),
    ('CROMOGLICATO DISSODICO', 'CROMOGLICATO', False),
    ('SESQUIHIDRATADO', '', False),
    ('HEPTAHIDRATADO', '', False),
    ('( FRAGMENTADA E INATIVADA )', '(FRAGMENTADA E INATIVADA)', False),
    ('(FRAGMENTADA, INATIVADA)', '(FRAGMENTADA E INATIVADA)', False),
    ('SESQUI-HIDRATADA', '', False),
    ('(PORT 344/98 LISTA C 1)', '', False),
    ('PENTAHIDRATADO', '', False),
    ('GETAMICINA', 'GENTAMICINA', False),
    ('VALERATO + BETAMETASONA', 'VALERATO DE BETAMETASONA', False),
    ('PENTAHIDRATADA', '', False),
    ('(PORT 344/98 LISTA C-1)', '', False),
    ('(PORT 344/98 - LISTA C-1)', '', False),
    ('O%', 'O', False),
    ('VALERATO DE BETAMETASONA/ SULFATO DE GENTAMICINA/ TOLNAFTATO CLIOQUINOL/', 
     'VALERATO DE BETAMETASONA + SULFATO DE GENTAMICINA + TOLNAFTATO + CLIOQUINOL', False),
    ('VALERATO DE BETAMETASONA/ SULFATO DE GENTAMICINA/ + TOLNAFTATO + CLIOQUINOL/', 
     'VALERATO DE BETAMETASONA + SULFATO DE GENTAMICINA + TOLNAFTATO + CLIOQUINOL', False),
    ('VALERATO DE BETAMETASONA + SULFATO DE GENTAMICINA + CLIOQUINOL + TOLNAFTATO', 
     'VALERATO DE BETAMETASONA + SULFATO DE GENTAMICINA + TOLNAFTATO + CLIOQUINOL', False),
]