# -*- coding: utf-8 -*-
"""
Dicionários de correção para padronização de princípios ativos.
Contém todas as regras de substituição e normalização.
"""

# ==============================================================================
#      DICIONÁRIO PRINCIPAL DE CORREÇÃO
# ==============================================================================

DICIONARIO_DE_CORRECAO = {
    "TRIIDRATADA": "",
    "BROMETRO": "BROMETO",
    "ACETO TRIA SULF NEO GRAM NIST": "ACETONIDO DE TRIANCINOLONA + SULFATO DE NEOMICINA + GRAMICIDINA + NISTATINA",
    "ATENOLOL CLORTALIDONA": "ATENOLOL + CLORTALIDONA",
    "ACETIL CISTEINA": "ACETILCISTEINA",
    "MONOFOSFATO DE RIBOFLAVINA SODICA": "FOSFATO SODICO DE RIBOFLAVINA",
    "ACETIL SALICILICO": "ACETILSALICILICO",
    "ACETIL-CISTEINA": "ACETILCISTEINA",
    "CLORFENAMINA": "CLORFENIRAMINA",
    "ESPIRINOLACTONA": "ESPIRONOLACTONA",
    "N ACETIL CISTEINA": "ACETILCISTEINA",
    "AXETIL CEFUROXIMA": "AXETILCEFUROXIMA",
    "MESSALAZINA": "MESALAZINA",
    "SULFOGUAICOL": "SULFOGUAIACOL",
    "ALENDRONATO SODICO": "ALENDRONATO DE SODIO",
    "ADEFOVIR DIVIPOXILA": "ADEFOVIR DIPIVOXILA",
    "DIGLICONATO DE CLOREXIDINA": "DIGLUCONATO DE CLOREXIDINA",
    "BUTIL BROMETO DE ESCOPOLAMINA": "BUTILBROMETO DE ESCOPOLAMINA",
    "DOCETAXOL": "DOCETAXEL",
    "ATOSIBANO": "ATOSIBANA",
    "HIDROBROMETO DE CITALOPRAM": "BROMIDRATO DE CITALOPRAM",

    # Padronização de Nomenclatura e Sufixos
    "TRIPTOFANA": "TRIPTOFANO",
    "LOSARTAN POTASSICO": "LOSARTANA POTASSICA",
    "BASILIXIMAB": "BASILIXIMABE",
    "GEFITINIB": "GEFITINIBE",
    "TOLCAPONE": "TOLCAPONA",
    "L ARGININA": "ARGININA",
    "SULBACTAM SODICA": "SULBACTAM SODICO",
    "CETOROLACO TROMETAMINA": "CETOROLACO TROMETAMOL",
    "TROMETAMOL CETOROLACO": "CETOROLACO TROMETAMOL",
    "DICLOFENACO DE SODIO": "DICLOFENACO SODICO",
    "DICLOFENACO DE POTASSIO": "DICLOFENACO POTASSICO",
    "NITRATO CEROSO": "NITRATO DE CERIO",
    "LAURILSULFATO": "LAURIL SULFATO",

    # Padronização de Formas Hidratadas/Sal
    "TRIIDRATADO": "",
    "TRI HIDRATADO": "",
    "TRI HIDRATADA": "",
    "DI HIDRATADO": "",
    "DI HIDRATADA": "",
    "DIIDRATADO": "",
    "DIIDRATADA": "",
    "TRIHIDRATADO": "",
    "TRIHIDRATADA": "",
    "DIHIDRATADO": "",
    "DIHIDRATADA": "",
    "SESQUI HIDRATADO": "SESQUIDRATADO",
    "SESQUI HIIDRATADO": "SESQUIDRATADO",
    "SESQUI-HIDRATADO": "SESQUIDRATADO",
    "SESQUI HIDRATADA": "SESQUIDRATADO",
    "SESQUIIDRATADA": "SESQUIDRATADO",
    "HEMI HIDRATADO": "HEMI-HIDRATADO",
    "HEMIDRATADO": "HEMI-HIDRATADO",
    "HEMIIDRATADO": "HEMI-HIDRATADO",
    "MONOIDRATADO": "MONOHIDRATADO",
    "MONOIDRATADA": "MONOHIDRATADA",
    "TETRAIDRATADO": "TETRAHIDRATADO",
    "PENTAIDRATADO": "PENTAHIDRATADO",
    "PENTAIDRATADA": "PENTAHIDRATADA",
    "HEXA HIDRATADO": "HEXAHIDRATADO",
    "HEPTA HIDRATADO": "HEPTAHIDRATADO",
    "HEPTAIDRATADO": "HEPTAHIDRATADO",
    "DIIDROERGOTAMINA": "DI-HIDROERGOTAMINA",
    "DI HIDROERGOTAMINA": "DI-HIDROERGOTAMINA",

    # Remoção de Informações Adicionais e Simplificação
    "CIANOCOBALAMINA 0 1": "CIANOCOBALAMINA",
    "DEXTRANA 70 99M TC": "DEXTRANA",
    "ACIDO ASCORBICO 90": "ACIDO ASCORBICO",
    "METIONINA 11 C": "METIONINA",
    "PANAX GINSENG C A MEY": "PANAX GINSENG",
    "AMOXICILINA BASE": "AMOXICILINA",
    "COLCHICINA BASE": "COLCHICINA",
    "AGUA PARA INJETAVEIS QSP": "AGUA PARA INJETAVEIS",
    "AGUA PARA INJECAO Q S P": "AGUA PARA INJECAO",
    "GINKGO BILOBA L": "GINKGO BILOBA",
    "AESCULUS HIPPOCASTANUM L": "AESCULUS HIPPOCASTANUM",
    "HEDERA HELIX L": "HEDERA HELIX",
    "CYNARA SCOLYMUS L": "CYNARA SCOLYMUS",
    "PASSIFLORA INCARNATA L": "PASSIFLORA INCARNATA",
    "VALERIANA OFFICINALIS L": "VALERIANA OFFICINALIS",
    "ECHINACEA PURPUREA L MOENCH": "ECHINACEA PURPUREA",
    "MAYTENUS ILICIFOLIA MART EX REISS": "MAYTENUS ILICIFOLIA",
    "CASSIA ANGUSTIFOLIA VAHL": "CASSIA ANGUSTIFOLIA",
    "PAPAVER SOMNIFERUM L": "PAPAVER SOMNIFERUM",
    "MELILOTUS OFFICINALIS LAM": "MELILOTUS OFFICINALIS",
    "MELILOTUS OFFICINALIS L PALL": "MELILOTUS OFFICINALIS",
    "CASSIA FISTULA L": "CASSIA FISTULA",
    "CENTELLA ASIATICA L URB": "CENTELLA ASIATICA",
    "CENTELLA ASIATICA URB": "CENTELLA ASIATICA",
    "LAM MIERS": "MIERS",
    ".": "",
    "NC NI": "NAO ESPECIFICADO",
    "NI NC": "NAO ESPECIFICADO",
    "NI": "NAO ESPECIFICADO",
    "NAN": "NAO ESPECIFICADO",
    "PRODUTOS SEM SUBSTANCIA ESPECIFICA": "NAO ESPECIFICADO",

    # Correção de abreviações encontradas em associações
    "CLORIDRATO DE PI": "CLORIDRATO DE PIRIDOXINA",
    "FOSFATO DE CALCI": "FOSFATO DE CALCIO",
    "GLICONATO DE MAG": "GLICONATO DE MAGNESIO",
    "GLICONATO DE POT": "GLICONATO DE POTASSIO",
    "NITRATO DE TIAMI": "NITRATO DE TIAMINA",
    "PALMITATO DE RET": "PALMITATO DE RETINOL",
    "PANAX GINSENG C": "PANAX GINSENG",
    "PANTOTENATO DE C": "PANTOTENATO DE CALCIO",
    "SULFATO DE MANGA": "SULFATO DE MANGANES",
    "HEMIDRATO DE ESTRADIOL": "ESTRADIOL HEMI-HIDRATADO",
    "GONADOTROFINA CORIONICA": "GONADOTROPINA CORIONICA",

    # Remoção de redundâncias
    "AMOXICILINA + AMOXICILINA TRI HIDRATADA": "AMOXICILINA",
    "BETAISTINA + CLORIDRATO DE BETAISTINA": "CLORIDRATO DE BETAISTINA",
    "ACETATO DE DEXAMETASONA + DEXAMETASONA": "ACETATO DE DEXAMETASONA",
    "CLORIDRATO DE IMIPRAMINA + IMIPRAMINA": "CLORIDRATO DE IMIPRAMINA",
    "CITALOPRAM + CITALOPRAM HIDROBROMETO": "BROMIDRATO DE CITALOPRAM",

    # REMOVENDO SAL
    "FORMOTEROL DIHIDRATADO": "FORMOTEROL",
    "SAXAGLIPTINA MONOHIDRATADA": "SAXAGLIPTINA",
    "SIBUTRAMINA MONOHIDRATADO": "SIBUTRAMINA",
    "ROPIVACAINA MONOHIDRATADO": "ROPIVACAINA",
    "ONDANSETRONA DIHIDRATADO": "ONDANSETRONA",
    "MOXIFLOXACINO MONOHIDRATADO": "MOXIFLOXACINO",
    "MONOHIDRATADO": "",
    "ANIDRA": "",
    "MONOHIDRATADA": "",
    "CITALOPRAM HIDROBROMETO": "CITALOPRAM",
    "PIPERACILINA SODICA": "PIPERACILINA",
    "TAZOBACTAM SODICO": "TAZOBACTAM",
    "PEMETREXEDE DISSODICO": "PEMETREXEDE",
    "DOLUTEGRAVIR SODICO": "DOLUTEGRAVIR",
    "RALTEGRAVIR POTASSICO": "RALTEGRAVIR",
    "POLICARBOFILA CALCICA": "POLICARBOFILA",
    "SULBACTAM SODICO": "SULBACTAM",
    "GANCICLOVIR SODICO": "GANCICLOVIR",
    "FOSFATO DISSODICO DE DEXAMETASONA": "FOSFATO DE DEXAMETASONA",
    "FOSFATO SODICO DE RIBOFLAVINA": "RIBOFLAVINA",

    # Correções ortográficas e substituições específicas
    "FOMOTEROL": "FORMOTEROL",
    "SESQUIIDRATADO": "SESQUIHIDRATADO",

    # Deduplicações e fusões de compostos repetidos
    "SULBACTAM + SULBACTAM": "SULBACTAM",
    "CITALOPRAM + CITALOPRAM": "CITALOPRAM",

    # Ajustes de compostos mal formatados
    "BACITRACINA +": "BACITRACINA ZINCICA +",

    # Termos supérfluos (remoção direta)
    "TAMPONADA": "",
    "HEMIEPTAIDRATADO": "",
    "HEPTAHIDRATADO": "",
    "HEMIPENTAIDRATADO": "",
}

# ==============================================================================
#      DICIONÁRIO SUGERIDO (FUZZY MATCHING)
# ==============================================================================

DIC_SUGERIDO_ATIVO = {
    "PANTOPRAZOL + PANTOPRAZOL SODICO": "PANTOPRAZOL MAGNESICO + PANTOPRAZOL SODICO",
    "NIFEDIPINA": "NIFEDIPINO",
    "MICOFENOLATO SODICO": "MICOFENOLATO DE SODIO",
    "CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + CLORIDRATO DE TIAMINA + DEXAMETASONA": "ACETATO DE DEXAMETASONA + CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + CLORIDRATO DE TIAMINA",
    "ACETATO DE DEXAMETASONA + CIANOCOBALAMINA + PIRIDOXINA + TIAMINA": "ACETATO DE DEXAMETASONA + CIANOCOBALAMINA + CLORIDRATO DE PIRIDOXINA + CLORIDRATO DE TIAMINA",
    "DEXAMETASONA + FUMARATO DE CLEMASTINA": "ACETATO DE DEXAMETASONA + FUMARATO DE CLEMASTINA",
    "CLIOQUINOL + HIDROCORTISONA": "ACETATO DE HIDROCORTISONA + CLIOQUINOL",
    "TRIANCINOLONA ACETONIDA": "ACETONIDA DE TRIANCINOLONA",
    "ACIDO SALICILICO + DIPROPIONATO DE BETAMETASONA": "ACIDO ACETILSALICILICO + DIPROPIONATO DE BETAMETASONA",
    "ACIDO AMINOCAPROICO": "ACIDO EPSILON AMINOCAPROICO",
    "AMOXICILINA + AMOXICILINA": "AMOXICILINA",
    "AMOXICILINA + CLARITROMICINA + ESOMEPRAZOL": "AMOXICILINA + CLARITROMICINA + ESOMEPRAZOL MAGNESICO",
    "AMOXICILINA + SULBACTAM PIVOXILA": "AMOXICILINA SODICA + SULBACTAM PIVOXILA",
    "AMOXICILINA SODICA + SULBACTAM": "AMOXICILINA SODICA + SULBACTAM PIVOXILA",
    "ANFOTERICINA B + TETRACICLINA": "ANFOTERICINA B + CLORIDRATO DE TETRACICLINA",
    "APROTININA + FATOR XIII + FIBRINOGENIO + TROMBINA": "APROTININA + FATOR XIII DE COAGULACAO + FIBRINOGENIO + TROMBINA",
    "IBUPROFENO ARGININA": "ARGININA + IBUPROFENO",
    "BACITRACINA + SULFATO DE NEOMICINA": "BACITRACINA ZINCICA + SULFATO DE NEOMICINA",
    "BETAMETASONA + CETOCONAZOL + SULFATO DE NEOMICINA": "CETOCONAZOL + DIPROPIONATO DE BETAMETASONA + SULFATO DE NEOMICINA",
    "BETAMETASONA + DEXCLORFENIRAMINA": "BETAMETASONA + MALEATO DE DEXCLORFENIRAMINA",
    "CAFEINA + CARISOPRODOL + DICLOFENACO + PARACETAMOL": "CAFEINA + CARISOPRODOL + DICLOFENACO SODICO + PARACETAMOL",
    "CAFEINA + DIPIRONA + ISOMETEPTENO": "CAFEINA + CLORIDRATO DE ISOMETEPTENO + DIPIRONA",
    "CALAMINA + CANFORA + CLORIDRATO DE DIFENIDRAMINA": "CALAMINA + CANFORA (2-BORNANONA) + CLORIDRATO DE DIFENIDRAMINA",
    "CARBONATO CALCIO + COLECALCIFEROL": "CARBONATO DE CALCIO + COLECALCIFEROL",
    "CIPROFLOXACINO + HIDROCORTISONA": "CLORIDRATO DE CIPROFLOXACINO + HIDROCORTISONA",
    "CLORIDRATO DE LIDOCAINA + LIDOCAINA": "CLORIDRATO DE LIDOCAINA",
    "COLECALCIFEROL + OXIDO DE ZINCO + RETINOL": "COLECALCIFEROL + OXIDO DE ZINCO + PALMITATO DE RETINOL",
    "CUMARINA + HEPARINA SUINA": "CUMARINA + HEPARINA SODICA SUINA",
    "DICLOFENACO + DICLOFENACO DIETILAMONIO": "DICLOFENACO DIETILAMONIO + DICLOFENACO POTASSICO",
    "GLICONATO DE CLOREXIDINA": "DIGLUCONATO DE CLOREXIDINA",
    "AGUA ESTERIL PARA INJECAO": "AGUA PARA INJECAO",
    "MELILOTUS OFFICINALIS (L) PALL": "MELILOTUS OFFICINALIS",
    "POLICRESULENO A 36%": "POLICRESULENO",
    "CENTELLA ASIATICA (L) URB": "CENTELLA ASIATICA",
    "DICLORIDRATO DE BUCLIZINA": "CLORIDRATO DE BUCLIZINA",
    "LATANOPROSTA + MALEATO ACIDO DE TIMOLOL": "LATANOPROSTA + MALEATO DE TIMOLOL",
    "MALEATO ACIDO DE TIMOLOL": "MALEATO DE TIMOLOL",
    "MALEATO ACIDO DE TIMOLOL + TRAVOPROSTA": "MALEATO DE TIMOLOL + TRAVOPROSTA",
    "SACCHAROMYCES BOULARDII - 17": "SACCHAROMYCES BOULARDII",
    "SULFAMETOXAZOL + SULFATO DE TRIMETOPRIMA": "SULFAMETOXAZOL + TRIMETOPRIMA",
    "ACAROS + ANTIGENOS BACTERIANAS SOB A FORMA DE LISADO + FUNGOS DO AR + LA DE CARNEIRO": "ACAROS + ANTIGENOS BACTERIANAS SOB A FORMA DE LISADO + FUNGOS DE AR + LA DE CARNEIRO",
    "ESOMEPRAZOL MAGNESIO": "ESOMEPRAZOL MAGNESICO",
    "DICLORIDRATO DE BETAISTINA": "CLORIDRATO DE BETAISTINA",
    "DICLORIDRATO DE FLURAZEPAM": "CLORIDRATO DE FLURAZEPAM",
    "DICLORIDRATO DE HIDROXIZINA": "CLORIDRATO DE HIDROXIZINA",
    "HYPERICUM PERFORATUM L": "HYPERICUM PERFORATUM",
    "JATEORHIZA PALMATA (LAM) MIERS + MAYTENUS ILICIFOLIA MARTEXREISS": "JATEORHIZA PALMATA MIERS + MAYTENUS ILICIFOLIA MARTEXREISS",
    "ASPARTATO DE L-ARGININA": "ASPARTATO DE ARGININA",
    "21-ACETATO DE DEXAMETASONA + CLOTRIMAZOL": "ACETATO DE DEXAMETASONA + CLOTRIMAZOL",
    "ALFA-AGALSIDASE": "ALFAGALSIDASE",
    "AMOXICILINA SODICA + CLAVULANATO DE POTASSIO": "AMOXICILINA + CLAVULANATO DE POTASSIO",
    "BESILATO DE AMLODIPINA + RAMIPRIL": "BESILATO DE ANLODIPINO + RAMIPRIL",
    "CLORATO DE SODIO": "CLORETO DE SODIO",
    "ETOPOSIDO": "ETOPOSIDEO",
    "GLICLAZIDA": "GLICAZIDA",
    "VIRUS DA HEPATITE A PURIFICADO INATIVADO": "VIRUS DA HEPATITE A INATIVADO",
    "VIRUS DA VARICELA -ZOSTER": "VIRUS DA VARICELA",
}

# ==============================================================================
#      CORREÇÕES DIRECIONADAS (str.replace)
# ==============================================================================

CORRECOES_CONTAINS = [
    ('.', '', False),
    ('TRI-HIDRATADA', '', False),
    ('TRI-HIDRATADO', '', False),
    ('DI-HIDRATADA', '', False),
    ('DI-HIDRATADO', '', False),
    ('SESQUI-HIIDRATADO', '', False),
    ('SESQUIDRATADO', '', False),
    ('SESQUIHIDRATADO', '', False),
    ('SESQUI-HIDRATADA', '', False),
    ('(PORT 344/98 LISTA C 1)', '', False),
    ('PENTAHIDRATADO', '', False),
    ('PENTAHIDRATADA', '', False),
    ('O%', 'O', False),
]

# ==============================================================================
#      COLUNAS PARA NORMALIZAÇÃO (REMOÇÃO DE ACENTOS)
# ==============================================================================

COLUNAS_PARA_NORMALIZAR = [
    'PRINCIPIO ATIVO',
    'LABORATORIO',
    'PRODUTO',
    'APRESENTACAO',
]